import QtQuick 2.7
import QtQuick.Controls 2.2

ScrollView {
    id: root
    signal clicked()

    TextArea {

        text: qsTr(
"<h2>Il Fu Mattia Pascal</h2>
<p>Il fu Mattia Pascal è un celebre romanzo di Luigi Pirandello che apparve dapprima a puntate sulla rivista Nuova Antologia nel 1904 e che fu pubblicato in volume nello stesso anno. Fu il primo grande successo di Pirandello, scritto in un momento difficile della sua vita.</p>
<h2>Trama</h2>
<p>Mattia Pascal vive a Miragno, dove il padre ha lasciato in eredità la miniera di zolfo alla moglie e ai due figli. Batta Malagna, un disonesto amministratore, si interessa di gestire il patrimonio. Egli sposa Oliva, ragazza che Mattia conosce bene, con la quale intraprende una relazione adultera al fine di fare un dispetto all'amministratore poiché questo non riesce ad avere eredi e attribuisce la colpa di ciò ad Oliva, non pensando che invece sia lui il \"problema\". Alla fine Oliva rimane incinta di un bambino, figlio di Mattia. L'amico Pomino dice al protagonista di aver origliato una discussione con una serva, scoprendo così che Malagna sta tramando qualcosa con la sorella, Marianna Dondi, vedova Pescatore; questa gli avrebbe rimproverato di non riuscire ad avere un figlio, conseguenza dovuta al rifiuto di sposare Romilda, figlia della vedova e nipote di Malagna, di cui Pomino è innamorato.</p>
<p>Ora lo zio si sarebbe pentito di non aver accontentato la nipote. Mattia e Pomino temono che l'uomo stia combattendo con la cugina per avere un figlio da Romilda. Pascal aiuta l'amico, e, giusto per stordirlo un po', gli dice che, per salvare la giovane, Pomino potrebbe sposarla. Con la scusa di una cambiale, Mattia si reca a casa di Marianna Dondi, dove trova anche Malagna. Conosce Romilda. Si trattiene poco a casa della vedova Pescatore, per poter tornare ancora da Romilda e dalla madre, che, però, non sembra contenta dell'annuncio di una sua prossima visita.</p>
<p>Nonostante il giovane le parli di Pomino, Romilda si innamora di Mattia, e lui ricambia l'amore. Un giorno, la ragazza, rimasta sola con lui dopo che la madre si è allontanata, gli chiede di portarla via. Romilda viene messa incinta da Mattia e lui, in seguito al loro rapporto sessuale, pensa come preparare la madre alla notizia del suo inevitabile matrimonio. Riceve, però, una lettera da Romilda, in cui lei gli dice che non devono più vedersi. Mattia non comprende il motivo che ha spinto la giovane a chiedergli una cosa simile. Oliva si reca a casa sua per sfogarsi con la madre di Mattia per la disperazione cagionatale dal marito. Batta Malagna ha annunciato il prossimo arrivo del suo tanto atteso figlio.</p>
<p>Mattia, compresa la ragione per cui Romilda gli ha detto che non avrebbero dovuto più vedersi, si sente ingannato da lei. Si reca così a casa di Oliva e le mostra la lettera. La ragazza capisce che Malagna non è il vero padre del bambino che aspetta Romilda, ma Mattia le dice che lei deve far credere al marito che lui può veramente avere un figlio e la mette incinta. Malagna scopre il tradimento della moglie, va da Mattia e gli dice che ha disonorato la nipote e che deve rimediare a quello che ha fatto.</p>
<p>Il protagonista capisce che Romilda non ha fatto nulla di male per far credere a Malagna di essere il padre del bambino che lei aspetta. La ragazza, infatti, sostiene che quando ha rivelato alla madre l'amore che ormai la legava indissolubilmente a Mattia, Marianna Dondi è andata su tutte le furie, e le ha detto che non avrebbe mai acconsentito a farla sposare con uno «scioperato». Giunto Batta Malagna, la vedova Pescatore lascia sola Romilda con lui. La giovane gli rivela la sciagura che le è capitata e gli chiede di opporsi alla madre e di \"indurla a più giusti consigli\", dato che lei voleva restare fedele a Mattia. L'uomo si intenerisce, ma non troppo; le dice che, essendo Romilda minorenne, è ancora sotto la potestà della madre e che potrebbe anche agire giudiziariamente contro Pascal ma giunge ad un compromesso accettando come suo il figlio che sarebbe nato da Romilda. Ora però che anche la moglie è incinta dovrà fare da padre al bambino che Oliva aspetta da Mattia.</p>
<p>Mattia quindi è costretto a sposare Romilda che è invidiosa del figlio che sarebbe nato ad Oliva tra gli agi, al contrario del suo che verrà al mondo nell'incertezza del domani, e \"non può vedere Mattia\". Per salvare il podere della Stia col mulino, i Pascal devono vendere le case, e la madre del protagonista va a vivere con il figlio. Ma questo non basta. Pascal cerca di trovare un'occupazione, ma non ci riesce. La vedova Pescatore e Romilda non si dimostrano gentili con la madre di Mattia, e lui teme che, irritate dalla guardia che il giovane fa alla madre, la trattino male. Zia Scolastica, membro nubile della famiglia, presentata ad inizio dell'opera, la porta via. Un giorno, verso sera, Pascal incontra per caso Pomino. Egli è adirato con Mattia per il suo tradimento, ma il protagonista cerca di convincerlo che è stato Pomino a tradirlo, dato il sacrificio che deve compiere vivendo con Romilda e la vedova Pescatore. L'amico gli trova un lavoro: suo padre, entrato nel municipio, dice che la biblioteca di Boccamazza è in misere condizioni, e colui che se ne occupa è fisicamente debole.</p>
<p>Grazie a Pomino, Mattia diventa bibliotecario. Un giorno, gli giunge notizia che la moglie sta per dare alla luce il bambino. Lui si precipita a casa, dove Marianna Dondi gli dice di andare a cercare un medico. Dopo aver girato invano, Mattia, esausto, torna a casa, e vi trova il dottore. Pascal vede che sono due bambine quelle che Romilda gli sta dando: una è già nata, l'altra sta per venire al mondo. Una delle figlie muore a pochi giorni dalla nascita, l'altra quando ha quasi un anno. Con la piccola viene a mancare anche la madre di Mattia, nello stesso giorno e quasi nella stessa ora. Una notte intera Mattia vaga per il paese e le campagne, e alla fine si ritrova nel podere della Stia, presso la gora del mulino.</p>
<p>Viene aiutato da un vecchio mugnaio di nome Filippo, che lo fa sedere sotto un albero e gli parla della madre e del padre del protagonista. L'uomo lo consola, gli dice che non deve piangere e disperarsi così, perché la figlia è stata accolta nel «mondo di là» dalla sua nonna, che le parlerà sempre di lui e non l'abbandonerà mai. Dopo una delle consuete liti con Romilda e la vedova Pescatore, che dopo la morte della sua bambina e della madre lo disgustavano, non riuscendo più a resistere alla sua miserabile vita, Mattia fugge dal paese. Strada facendo, pensa di recarsi a Marsiglia, da cui avrebbe potuto partire per l'America. Ma giunto a Nizza si ferma davanti ad una bottega, dove sono esposti opuscoli che pubblicizzano il gioco della roulette. All'inizio si allontana dalla bottega, ma poi vi entra e, per curiosità, compra un opuscolo. Quindi parte per Montecarlo. Arrivato qui, si ferma a giocare alla roulette, e, con sua sorpresa, vince.</p>
<p>Mattia continua a vincere e diventa ricco. Dati i suoi colpi fortunati, una donna gli propone di giocare con lei, ma il giovane Pascal la respinge. Anche uno «spagnuolo» gli porge la stessa richiesta, e lui, dopo averci parlato, se ne allontana. La mattina del dodicesimo giorno, Mattia viene a sapere che qualcuno si è ucciso: è un giovinetto che il protagonista conosceva, avendo entrambi giocato una volta allo stesso tavolino. Pascal ne copre pietosamente il viso con un fazzoletto, e fugge, ritornando a Nizza per partirne il giorno stesso. Deciso a ritornare a casa per riscattare i suoi averi e vendicarsi dei soprusi della suocera, un altro fatto muta il suo destino. Mentre è in treno legge per caso su un giornale che a Miragno è stato ritrovato nella roggia di un mulino il cadavere di Mattia Pascal, scomparso da molti giorni, suicidatosi per dissesti finanziari.</p>
<p>Sebbene sconvolto, comprende presto che, credendolo tutti morto, può avere un'altra vita. Così, con lo pseudonimo di Adriano Meis inizia a viaggiare in Italia e poi all'estero. Infine, decide di stabilirsi a Roma in una camera ammobiliata. Si innamora, ricambiato, di Adriana, la dolce e mite figlia del padrone di casa, Anselmo Paleari, e vuole sposarla, tentando di dar luogo ad una nuova vita stabile. Ma ben presto si rende conto che la sua esistenza è fittizia. Infatti, non essendo registrato all'anagrafe, non può sposare Adriana, non può denunciare il furto subìto da Terenzio Papiano, un losco individuo penetrato nella sua stanza per rubare del denaro, e non può svolgere alcuna delle normali attività quotidiane, poiché privo di identità. Finge così un suicidio e, lasciato il suo bastone e il suo cappello vicino a un ponte del Tevere, ritorna a Miragno sotto il nome di Mattia Pascal.</p>
<p>Sono intanto trascorsi due anni e arrivato al paese, Mattia scopre che la moglie si è risposata con Pomino e ha avuto una bambina. Si ritira così dalla vita e trascorre le sue giornate nella biblioteca polverosa dove lavorava in precedenza a scrivere la sua storia e ogni tanto si reca al cimitero per portare sulla tomba del \"fu Mattia Pascal\" una corona di fiori. Nella Premessa seconda (filosofica) a mo' di scusa il protagonista decide di mettere per iscritto la sua strana vicenda: Mattia lascerà il manoscritto nella biblioteca dove aveva lavorato con l'obbligo però di aprirlo soltanto cinquant'anni dopo la sua terza, ultima e definitiva morte. La prima morte è quella che lo vede morto suicida nel mulino della \"Stìa\", la seconda quella in cui \"muore\" il suo alter ego Adriano Meis. Il consiglio di mettere per scritto il suo caso viene a Mattia dal suo amico bibliotecario, don Eligio.</p>
")
        textFormat: Text.RichText
        wrapMode: Text.WordWrap
        horizontalAlignment: Text.AlignLeft

        MouseArea {
            anchors.fill: parent
            onClicked: root.clicked()
        }
    }
}
